package com.prodspace.fre_rule_cc1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoggingInvocationHandler implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public LoggingInvocationHandler() {
    }




}