package com.myspace.githook_1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AnotherAssets implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public AnotherAssets() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public AnotherAssets(java.lang.String name) {
		this.name = name;
	}

}