package com.myspace.githook_1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CountryResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String notes;

	public CountryResult() {
	}

	public java.lang.String getNotes() {
		return this.notes;
	}

	public void setNotes(java.lang.String notes) {
		this.notes = notes;
	}

	public CountryResult(java.lang.String notes) {
		this.notes = notes;
	}

	@Override
	public String toString() {
		return "CountryResult [notes=" + notes + "]";
	}
	
	

}