package com.myspace.githook_1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CountryResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String message;

	public CountryResult() {
	}

	@Override
	public String toString() {
		return "CountryResult [notes=" + notes + "]";
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public CountryResult(java.lang.String message) {
		this.message = message;
	}

}