package com.myspace.githook_1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CountryObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String countryName;
	private java.lang.String countryCode;

	public CountryObject() {
	}

	public java.lang.String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(java.lang.String countryName) {
		this.countryName = countryName;
	}

	public java.lang.String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(java.lang.String countryCode) {
		this.countryCode = countryCode;
	}

	public CountryObject(java.lang.String countryName,
			java.lang.String countryCode) {
		this.countryName = countryName;
		this.countryCode = countryCode;
	}

}