package com.myspace.githook_1;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class ShipmentDataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String countryCode;
	private java.lang.String countryNotes;

	private java.lang.String countryName;

	private java.lang.String countryColor;

	public ShipmentDataObject() {
	}

	public java.lang.String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(java.lang.String countryCode) {
		this.countryCode = countryCode;
	}

	public java.lang.String getCountryNotes() {
		return this.countryNotes;
	}

	public void setCountryNotes(java.lang.String countryNotes) {
		this.countryNotes = countryNotes;
	}

	public java.lang.String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(java.lang.String countryName) {
		this.countryName = countryName;
	}

	public java.lang.String getCountryColor() {
		return this.countryColor;
	}

	public void setCountryColor(java.lang.String countryColor) {
		this.countryColor = countryColor;
	}

	public ShipmentDataObject(java.lang.String countryCode,
			java.lang.String countryNotes, java.lang.String countryName,
			java.lang.String countryColor) {
		this.countryCode = countryCode;
		this.countryNotes = countryNotes;
		this.countryName = countryName;
		this.countryColor = countryColor;
	}

}
