package com.myspace.githook_1;

/**
 * This class was automatically generated by the data modeler tool.
 */
https://github.com/healez/GIT1/blob/master/src/main/java/com/myspace/githook_1/ShipmentDataObject.java
public class ShipmentDataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String countryCode;
	private java.lang.String countryName;
	private java.lang.String countryNotes;


	public ShipmentDataObject() {
	}

	public java.lang.String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(java.lang.String countryCode) {
		this.countryCode = countryCode;
	}

	public java.lang.String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(java.lang.String countryName) {
		this.countryName = countryName;
	}

	public java.lang.String getCountryNotes() {
		return this.countryNotes;
	}

	public void setCountryNotes(java.lang.String countryNotes) {
		this.countryNotes = countryNotes;
	}

	public ShipmentDataObject(java.lang.String countryCode,
			java.lang.String countryName, java.lang.String countryName) {
		this.countryCode = countryCode;
		this.countryName = countryName;
		this.countryNotes = countryNotes;
	}

}
