package com.myspace.githook_1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ShipmentDataObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ShipmentDataObject() {
    }




}