package com.myspace.githook_1;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class ShipmentObject implements java.io.Serializable, ShipmentObjectInterface {

	static final long serialVersionUID = 1L;

	@Override
	public String toString() {
		return "ShipmentObject [countryCode=" + countryCode + ", countryName=" + countryName + ", countryColor="
				+ countryColor + ", countryNumber=" + countryNumber + ", countryNotes=" + countryNotes + "]";
	}

	private java.lang.String countryCode;
	private java.lang.String countryName;
	private java.lang.String countryColor;
	private java.lang.String countryNumber;
	private java.lang.String countryNotes;

	public ShipmentObject() {
	}


	public ShipmentObject(java.lang.String countryCode,
			java.lang.String countryName, java.lang.String countryColor,
			java.lang.String countryNumber, java.lang.String countryNotes) {
		this.countryCode = countryCode;
		this.countryName = countryName;
		this.countryColor = countryColor;
		this.countryNumber = countryNumber;
		this.countryNotes = countryNotes;
	}


	@Override
	public String getCountryCode() {
		return countryCode;
	}


	@Override
	public void setCountryCode(String countryCode) {
		this.countryCode=countryCode;
	}


	@Override
	public String getCountryName() {
		return countryName;
	}


	@Override
	public void setCountryName(String countryName) {
		this.countryName=countryName;
		
	}

	@Override
	public String getCountryColor() {
		return countryColor;
	}


	@Override
	public void setCountryColor(String countryColor) {
		this.countryColor=countryColor;
	}


	@Override
	public String getCountryNumber() {
		return countryNumber;
	}


	@Override
	public void setCountryNumber(String countryNumber) {
		this.countryNumber=countryNumber;
	}
	
	@Override
	public String getCountryNotes() {
		return countryNotes;
	}


	@Override
	public void setCountryNotes(String countryNotes) {
		this.countryNotes = countryNotes;
	}	
}