package com.myspace.githook_1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Try implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public Try() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public Try(java.lang.String name) {
		this.name = name;
	}

}