package com.myspace.githook_1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TryLog implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String message;

	public TryLog() {
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public TryLog(java.lang.String message) {
		this.message = message;
	}

}